name: update-site

on:
  push:
    inputs:
      receiving_repo:
        description: 'Receiving repo workflow (notes-site) which will be triggered'
        default: 'notes-site'

      receiving_github_account:
        description: 'GitHub account owwner'
        default: 'regexyl'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch trigger to notes-site
        run: |
          curl -X POST https://api.github.com/repos/${{ inputs.receiving_github_account }}/${{ inputs.receiving_repo }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PAT }} \
          --data '{"event_type": "Trigger syncing of submodules on notes-site", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
