name: update-site

on: push

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch trigger to notes-site
        run: |
          curl -X POST https://api.github.com/repos/regexyl/notes-site/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PAT }} \
          --data '{"event_type": "Trigger syncing of submodules on notes-site", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
