name: update-site

on: push

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch trigger to notes-site
        run: |
curl -L \
-X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer 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" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/regexyl/notes-site/actions/workflows/sync-submdules.yml/dispatches \
-d '{"ref":"main"}'
curl -L \
-X POST \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/regexyl/notes-site/actions/workflows/sync-submdules.yml/dispatches \
-d '{"ref":"main"}'
