name: update-site

on: push

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch trigger to notes-site
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: regexyl/notes-site
          event-type: my-event