name: update-site

on: push

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch trigger to notes-site
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/regexyl/notes-site/actions/workflows/WORKFLOW_ID/dispatches \
          -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'
      - uses: actions/checkout@v3
